name: Build Windows Executable

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable
        run: |
          python build_app.py

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: WatermarkDetector-Windows
          path: dist/WatermarkDetector.exe
